#!/bin/bash
VERSION=$(cat extensions/jgit/.version 2>/dev/null || echo "0.0.0")
sed -e "s/packageVersion=\"@PACKAGE_VERSION@\"/packageVersion=\"$VERSION\"/g" -e "s/packageVersion=@PACKAGE_VERSION@/packageVersion=$VERSION/g"
