package org.us_ignite.thingworx.dap.runtime;

import com.thingworx.data.util.InfoTableInstanceFactory;
import com.thingworx.logging.LogUtilities;
import com.thingworx.types.InfoTable;
import com.thingworx.types.collections.ValueCollection;
import com.thingworx.types.primitives.BooleanPrimitive;
import com.thingworx.types.primitives.InfoTablePrimitive;
import com.thingworx.types.primitives.StringPrimitive;
import org.slf4j.Logger;

/** Generic, type-safe construction of the service result envelopes generated by DAP. */
public final class DapResults {
    private static final Logger LOGGER =
            LogUtilities.getInstance().getApplicationLogger(DapResults.class);

    private DapResults() {}

    /**
     * Creates a successful result using a row-count message.
     *
     * @param <T> the payload proxy type
     * @param serviceName the service name for logging
     * @param contract the payload service-result contract
     * @param payload the successful payload
     * @return the generated service-result InfoTable
     */
    public static <T extends DapDataShapeProxy<InfoTable>> InfoTable success(
            String serviceName, DapServiceContract<T> contract, T payload) {
        String message =
                serviceName + " completed with " + payload.toInfoTable().getRowCount() + " rows";
        LOGGER.info(message);
        return payloadResult(contract.shape(), false, message, payload.toInfoTable());
    }

    /**
     * Creates a successful result with an explicit message.
     *
     * @param <T> the payload proxy type
     * @param serviceName the service name for logging
     * @param message the success message
     * @param contract the payload service-result contract
     * @param payload the successful payload
     * @return the generated service-result InfoTable
     */
    public static <T extends DapDataShapeProxy<InfoTable>> InfoTable success(
            String serviceName, String message, DapServiceContract<T> contract, T payload) {
        LOGGER.info(serviceName + " completed: " + message);
        return payloadResult(contract.shape(), false, message, payload.toInfoTable());
    }

    /**
     * Creates a failed payload result from an exception.
     *
     * @param <T> the payload proxy type
     * @param serviceName the service name for logging
     * @param failure the service failure
     * @param contract the payload service-result contract
     * @return the generated service-result InfoTable
     */
    public static <T extends DapDataShapeProxy<InfoTable>> InfoTable failure(
            String serviceName, Throwable failure, DapServiceContract<T> contract) {
        String message = serviceName + " failed: " + failure;
        LOGGER.error(message);
        return payloadFailure(contract, message);
    }

    /**
     * Creates a failed payload result with an explicit message.
     *
     * @param <T> the payload proxy type
     * @param serviceName the service name for logging
     * @param message the failure message
     * @param contract the payload service-result contract
     * @return the generated service-result InfoTable
     */
    public static <T extends DapDataShapeProxy<InfoTable>> InfoTable failure(
            String serviceName, String message, DapServiceContract<T> contract) {
        LOGGER.error(serviceName + " failed: " + message);
        return payloadFailure(contract, message);
    }

    private static <T extends DapDataShapeProxy<InfoTable>> InfoTable payloadFailure(
            DapServiceContract<T> contract, String message) {
        try {
            InfoTable empty =
                    InfoTableInstanceFactory.createInfoTableFromDataShape(
                            contract.shape().payloadDataShapeName());
            return payloadResult(contract.shape(), true, message, empty);
        } catch (Exception exception) {
            throw new IllegalStateException("Unable to create DAP failure result", exception);
        }
    }

    /**
     * Creates a successful no-payload result.
     *
     * @param serviceName the service name for logging
     * @param message the optional success message
     * @param contract the no-payload service-result contract
     * @return the generated service-result InfoTable
     */
    public static InfoTable success(
            String serviceName, String message, DapNoPayloadServiceContract contract) {
        String resultMessage = message == null ? serviceName + " completed" : message;
        LOGGER.info(serviceName + " completed: " + resultMessage);
        return noPayloadResult(contract.shape(), false, resultMessage);
    }

    /**
     * Creates a failed no-payload result with an explicit message.
     *
     * @param serviceName the service name for logging
     * @param message the failure message
     * @param contract the no-payload service-result contract
     * @return the generated service-result InfoTable
     */
    public static InfoTable failure(
            String serviceName, String message, DapNoPayloadServiceContract contract) {
        LOGGER.error(serviceName + " failed: " + message);
        return noPayloadResult(contract.shape(), true, message);
    }

    /**
     * Creates a failed no-payload result from an exception.
     *
     * @param serviceName the service name for logging
     * @param failure the service failure
     * @param contract the no-payload service-result contract
     * @return the generated service-result InfoTable
     */
    public static InfoTable failure(
            String serviceName, Throwable failure, DapNoPayloadServiceContract contract) {
        String message = serviceName + " failed: " + failure;
        LOGGER.error(message);
        return noPayloadResult(contract.shape(), true, message);
    }

    private static InfoTable payloadResult(
            DapServiceResultShape shape, boolean error, String message, InfoTable payload) {
        if (!shape.hasPayload())
            throw new IllegalArgumentException("DAP result contract has no payload");
        try {
            InfoTable result =
                    InfoTableInstanceFactory.createInfoTableFromDataShape(
                            shape.resultDataShapeName());
            ValueCollection row = baseRow(error, message);
            row.put("Result", new InfoTablePrimitive(payload));
            result.addRow(row);
            return result;
        } catch (Exception exception) {
            throw new IllegalStateException(
                    "Unable to create " + shape.resultDataShapeName(), exception);
        }
    }

    private static InfoTable noPayloadResult(
            DapServiceResultShape shape, boolean error, String message) {
        if (shape.hasPayload()) {
            throw new IllegalArgumentException("DAP result contract declares a payload");
        }
        try {
            InfoTable result =
                    InfoTableInstanceFactory.createInfoTableFromDataShape(
                            shape.resultDataShapeName());
            result.addRow(baseRow(error, message));
            return result;
        } catch (Exception exception) {
            throw new IllegalStateException("Unable to create string result", exception);
        }
    }

    private static ValueCollection baseRow(boolean error, String message) {
        ValueCollection row = new ValueCollection();
        row.put("Message", new StringPrimitive(message));
        row.put("Error", new BooleanPrimitive(error));
        return row;
    }
}
