plugins {
    id 'thingworx.java-library'
    id 'thingworx.eclipse'
    id 'thingworx.spotless'
    id 'thingworx.publishing'
    id 'thingworx.sdk'
}

ext.publishingArtifactId = 'thingworx-dap-runtime'
ext.publishingName = 'ThingWorx DAP Runtime'
ext.publishingDescription = 'ThingWorx runtime helpers for ThingWorx DAP.'

sourceSets {
    main {
        java {
            srcDirs = ['src']
            exclude 'test/**'
        }
    }
    test {
        java.srcDirs = []
    }
}

dependencies {
    api project(':libraries:thingworx-dap')
    compileOnly fileTree(dir: project.ext.sdkExtractDir, include: '*.jar')
}

tasks.withType(JavaCompile).configureEach {
    dependsOn tasks.named('unpackSdk')
}
