{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "thingworx-operator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "thingworx-operator.name" . }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "thingworx-operator.name" . }}
{{- end }}
