plugins {
    id 'groovy'
    id 'java-gradle-plugin'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation localGroovy()
    testImplementation 'junit:junit:4.13.2'
}

gradlePlugin {
    plugins {
        gitHooks {
            id = 'thingworx.git-hooks'
            implementationClass = 'thingworx.VersioningPlugin'
        }
    }
}

group = 'io.github.us-ignite'
version = '0.1.0'
