plugins {
    id 'thingworx.java-library'
    id 'thingworx.eclipse'
    id 'thingworx.spotless'
    id 'thingworx.publishing'
}

ext.publishingArtifactId = 'thingworx-dap'
ext.publishingName = 'ThingWorx DAP'
ext.publishingDescription = 'Declarative annotation processor for ThingWorx entity XML.'

